"""Traceability: which tests verify which requirement, and on which target.

    python -m tools.trace           # print the matrix
    python -m tools.trace --write   # write docs/traceability.md
    python -m tools.trace --check   # exit 1 when a requirement has no test, or a test cites an unknown one

Requirements come from requirements/requirements.md, tests from the
@pytest.mark.requirement markers in tests/.
"""

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REQUIREMENTS = ROOT / "requirements" / "requirements.md"
TESTS = ROOT / "tests"
OUTPUT = ROOT / "docs" / "traceability.md"

ID_PATTERN = re.compile(r"^\| ([A-Z]+-\d+) \|", re.MULTILINE)
MARKER = re.compile(r"@pytest\.mark\.(\w+)(?:\((.*)\))?")


def requirement_ids():
    return ID_PATTERN.findall(REQUIREMENTS.read_text(encoding="utf-8"))


def tests():
    """Yield (file, test name, requirement IDs, target) for every test function."""
    for path in sorted(TESTS.glob("test_*.py")):
        text = path.read_text(encoding="utf-8")
        module_marks = set(re.findall(r"^pytestmark = pytest\.mark\.(\w+)", text, re.MULTILINE))
        pending = []
        for line in text.splitlines():
            marker = MARKER.match(line.strip())
            if marker:
                pending.append(marker.groups())
                continue
            function = re.match(r"def (test_\w+)\(([^)]*)", line)
            if function:
                marks = {name for name, _ in pending} | module_marks
                ids = [i for name, args in pending if name == "requirement" for i in re.findall(r'"([A-Z]+-\d+)"', args or "")]
                fixtures = function.group(2)
                if "sil_only" in marks or "release_bench" in fixtures or fixtures.strip() == "_libraries":
                    target = "simulation"
                elif "hil_only" in marks:
                    target = "board, manual" if "manual" in marks else "board"
                else:
                    target = "both"
                yield path.name, function.group(1), ids, target
                pending = []
            elif line and not line.startswith((" ", "@", "#", ")", "]")):
                pending = []


def matrix():
    known = requirement_ids()
    rows = {req: [] for req in known}
    unknown = []
    for file, name, ids, target in tests():
        for req in ids:
            if req in rows:
                rows[req].append((file, name, target))
            else:
                unknown.append((file, name, req))
    return rows, unknown


def render(rows):
    lines = [
        "# Traceability",
        "",
        "Generated by `python -m tools.trace --write`. Do not edit.",
        "",
        "| Requirement | Tests | On the board | Test |",
        "|---|---|---|---|",
    ]
    for req, entries in rows.items():
        if not entries:
            lines.append(f"| {req} | 0 | | **not verified** |")
            continue
        on_board = sum(target != "simulation" for _, _, target in entries)
        first = True
        for file, name, target in entries:
            note = "" if target == "both" else f" ({target} only)"
            head = f"| {req} | {len(entries)} | {on_board} |" if first else "| | | |"
            lines.append(f"{head} `{file}::{name}`{note} |")
            first = False
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description="Requirement to test traceability.")
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    rows, unknown = matrix()
    text = render(rows)
    if args.write:
        OUTPUT.write_text(text, encoding="utf-8", newline="\n")
        print(f"wrote {OUTPUT}")
    else:
        print(text)
    if args.check:
        missing = [req for req, entries in rows.items() if not entries]
        for req in missing:
            print(f"no test for {req}", file=sys.stderr)
        for file, name, req in unknown:
            print(f"{file}::{name} cites unknown requirement {req}", file=sys.stderr)
        stale = OUTPUT.exists() and OUTPUT.read_text(encoding="utf-8") != text
        if stale:
            print("docs/traceability.md is out of date: run python -m tools.trace --write", file=sys.stderr)
        sys.exit(1 if missing or unknown or stale else 0)


if __name__ == "__main__":
    main()
